/*eslint-disable*/
module.exports = {
    "creditCardDateDebitSummery": [
        {
            "debitAmount": 1996.95,
            "debitCurrencyCode": 0,
            "debitCurrencyDescription": "G\"Y",
            "debitDate": 20160802,
            "formattedDebitDate": "",
            "nextDebitEventOriginalCode": 0,
            "serviceCode": 0
        }
    ],
    "creditCardMyHomePageData": {
        "debitAmount": 1996.95,
        "joinPfm": true,
        "serviceCode": 0
    },
    "dates": [],
    "plasticCardAccountSummeryList": [
        {
            "debitAmount": 1996.95,
            "debitCurrencyCode": 0,
            "debitCurrencyDescription": "G\"Y",
            "paymentCashBack": 0,
            "serviceCode": 0
        }
    ],
    "plasticCardData": [
        {
            "plasticCardNumberWithoutPrefix": "353697216",
            "serviceCode": 0,
            "summary": {
                "current": {
                    "1": {
                        "serviceCode": 0,
                        "summariesByCurrencyCodes": {
                            "0": {
                                "serviceCode": 0,
                                "summaryDetails": {
                                    "20160802": {
                                        "accountCashBack": 0,
                                        "debitAmount": 1996.95,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "G\"Y",
                                        "debitDate": 20160802,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedStatementDate": "",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "partyComments": "7216",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 112,
                                        "plasticCardLable": "7216",
                                        "plasticCardNumberSuffix": "7216",
                                        "plasticCardNumberWithoutPrefix": 353697216,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "",
                                        "serviceCode": 0,
                                        "statementDate": 0,
                                        "statusDescription": "פעיל"
                                    }
                                }
                            }
                        }
                    }
                },
                "prev": {
                    "1": {
                        "serviceCode": 0,
                        "summariesByCurrencyCodes": {
                            "0": {
                                "serviceCode": 0,
                                "summaryDetails": {
                                    "20160703": {
                                        "accountCashBack": 0,
                                        "debitAmount": 9507.66,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160703,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "2016-07-03T00:00:00.000Z",
                                        "formattedStatementDate": "2016-07-10T00:00:00.000Z",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 0,
                                        "partyComments": "7216",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 0,
                                        "plasticCardLable": "",
                                        "plasticCardNumberSuffix": "7216",
                                        "plasticCardNumberWithoutPrefix": 353697216,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "1",
                                        "serviceCode": 0,
                                        "statementDate": 20160710,
                                        "statusDescription": ""
                                    }
                                }
                            }
                        }
                    },
                    "2": {
                        "serviceCode": 0,
                        "summariesByCurrencyCodes": {
                            "0": {
                                "serviceCode": 0,
                                "summaryDetails": {
                                    "20160703": {
                                        "accountCashBack": 0,
                                        "debitAmount": 908.26,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160703,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "2016-07-03T00:00:00.000Z",
                                        "formattedStatementDate": "2016-07-10T00:00:00.000Z",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 0,
                                        "partyComments": "7216",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 0,
                                        "plasticCardLable": "",
                                        "plasticCardNumberSuffix": "7216",
                                        "plasticCardNumberWithoutPrefix": 353697216,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "2",
                                        "serviceCode": 0,
                                        "statementDate": 20160710,
                                        "statusDescription": ""
                                    }
                                }
                            }
                        }
                    }
                },
                "serviceCode": 0
            },
            "vauchers": {
                "1": {
                    "serviceCode": 0,
                    "vauchersByCurrencyCodes": {
                        "0": {
                            "serviceCode": 0,
                            "vaucherDetails": {
                                "20160802": [
                                    {
                                        "clientBusinessName": "דומינוס פיצה",
                                        "debitAmount": 81.8,
                                        "debitAmountOffsetDiscount": 81.8,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 256,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160630,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-06-30T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 81.8,
                                        "originalSystemEventId": 431533786,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160630&eventSerialNumber=431533786&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 8501719,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "שופרסל אקספרסב מרמור",
                                        "debitAmount": 145.7,
                                        "debitAmountOffsetDiscount": 145.7,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 173,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160701,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-01T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 145.7,
                                        "originalSystemEventId": 432403244,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160701&eventSerialNumber=432403244&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 9002095,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "GETT",
                                        "debitAmount": 31.3,
                                        "debitAmountOffsetDiscount": 31.3,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 108,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160701,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-01T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 31.3,
                                        "originalSystemEventId": 432909273,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160701&eventSerialNumber=432909273&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 3695163,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "מקדולנדס רוטשילד ת\"א",
                                        "debitAmount": 50,
                                        "debitAmountOffsetDiscount": 50,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 256,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160702,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-02T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 50,
                                        "originalSystemEventId": 431880437,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160702&eventSerialNumber=431880437&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 3002051,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "10 ביס",
                                        "debitAmount": 103,
                                        "debitAmountOffsetDiscount": 103,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 205,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160702,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-02T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 103,
                                        "originalSystemEventId": 431891892,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160702&eventSerialNumber=431891892&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 5835811,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "ELAL INT ISRAEL",
                                        "debitAmount": 2204.71,
                                        "debitAmountOffsetDiscount": 2204.71,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 13,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160702,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-02T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 2204.71,
                                        "originalSystemEventId": 432228051,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160702&eventSerialNumber=432228051&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 5554041,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "ELAL INT ISRAEL",
                                        "debitAmount": 2204.71,
                                        "debitAmountOffsetDiscount": 2204.71,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 13,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160702,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-02T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 2204.71,
                                        "originalSystemEventId": 432228052,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160702&eventSerialNumber=432228052&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 5554042,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "KULI ALMA",
                                        "debitAmount": 32,
                                        "debitAmountOffsetDiscount": 32,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 14,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160702,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-02T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 32,
                                        "originalSystemEventId": 432984980,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160702&eventSerialNumber=432984980&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 2001255,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "RADIO E.P.G.B",
                                        "debitAmount": 29,
                                        "debitAmountOffsetDiscount": 29,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 97,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160702,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-02T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 29,
                                        "originalSystemEventId": 439145320,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160702&eventSerialNumber=439145320&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 2001348,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "KULI ALMA",
                                        "debitAmount": 29,
                                        "debitAmountOffsetDiscount": 29,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 14,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160703,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-03T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 29,
                                        "originalSystemEventId": 432985083,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160703&eventSerialNumber=432985083&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 3001093,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "GETT",
                                        "debitAmount": 31.2,
                                        "debitAmountOffsetDiscount": 31.2,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 108,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160703,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-03T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 31.2,
                                        "originalSystemEventId": 435911834,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160703&eventSerialNumber=435911834&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 2709841,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "טורק לחמגון",
                                        "debitAmount": 32,
                                        "debitAmountOffsetDiscount": 32,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 256,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160703,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-03T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 32,
                                        "originalSystemEventId": 435982387,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160703&eventSerialNumber=435982387&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 1001057,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "פיצוחי לב העיר",
                                        "debitAmount": 43,
                                        "debitAmountOffsetDiscount": 43,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 256,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160703,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-03T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 43,
                                        "originalSystemEventId": 438370534,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160703&eventSerialNumber=438370534&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 5001006,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "RADIO E.P.G.B",
                                        "debitAmount": 31,
                                        "debitAmountOffsetDiscount": 31,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 97,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160703,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-03T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 31,
                                        "originalSystemEventId": 439145321,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160703&eventSerialNumber=439145321&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 2001507,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "BREAKFAST CLUB",
                                        "debitAmount": 31,
                                        "debitAmountOffsetDiscount": 31,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 87,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160703,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-03T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 31,
                                        "originalSystemEventId": 439465062,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160703&eventSerialNumber=439465062&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 1175,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "BREAKFAST CLUB",
                                        "debitAmount": 32,
                                        "debitAmountOffsetDiscount": 32,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 87,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160703,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-03T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 32,
                                        "originalSystemEventId": 439465063,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160703&eventSerialNumber=439465063&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 1140,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "צומת ספרים ספריה",
                                        "debitAmount": 69,
                                        "debitAmountOffsetDiscount": 69,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 5,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160704,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-04T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 69,
                                        "originalSystemEventId": 438207677,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160704&eventSerialNumber=438207677&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 9001050,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "GETT",
                                        "debitAmount": 28.5,
                                        "debitAmountOffsetDiscount": 28.5,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 108,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160704,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-04T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 28.5,
                                        "originalSystemEventId": 438874108,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160704&eventSerialNumber=438874108&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 2719996,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "רנואר אופנה האנגר ת\"",
                                        "debitAmount": 49.9,
                                        "debitAmountOffsetDiscount": 49.9,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 4,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160704,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-04T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 49.9,
                                        "originalSystemEventId": 439177978,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160704&eventSerialNumber=439177978&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 6001013,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "האוזן חלילית",
                                        "debitAmount": 117,
                                        "debitAmountOffsetDiscount": 117,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 5,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160704,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-04T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 117,
                                        "originalSystemEventId": 439672296,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160704&eventSerialNumber=439672296&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 19005,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "פיצוחי לב העיר",
                                        "debitAmount": 35,
                                        "debitAmountOffsetDiscount": 35,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 256,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160704,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-04T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 35,
                                        "originalSystemEventId": 441280936,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160704&eventSerialNumber=441280936&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 6001021,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "טורק לחמגון",
                                        "debitAmount": 32,
                                        "debitAmountOffsetDiscount": 32,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 256,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160704,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-04T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 32,
                                        "originalSystemEventId": 441947481,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160704&eventSerialNumber=441947481&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 2001067,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "EAST דיקסי 120",
                                        "debitAmount": 75,
                                        "debitAmountOffsetDiscount": 75,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 256,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160705,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-05T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 75,
                                        "originalSystemEventId": 441176082,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160705&eventSerialNumber=441176082&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 1108,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "שופרסל אקספרסב מרמור",
                                        "debitAmount": 94.85,
                                        "debitAmountOffsetDiscount": 94.85,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 173,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160705,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-05T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 94.85,
                                        "originalSystemEventId": 441337704,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160705&eventSerialNumber=441337704&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 3002184,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "שופרסל אקספרסב מרמור",
                                        "debitAmount": 102,
                                        "debitAmountOffsetDiscount": 102,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 173,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160705,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-05T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 102,
                                        "originalSystemEventId": 441337705,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160705&eventSerialNumber=441337705&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 3002186,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "סופר פארם דיזנגוף סנ",
                                        "debitAmount": 323.8,
                                        "debitAmountOffsetDiscount": 323.8,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 230,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160706,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-06T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 323.8,
                                        "originalSystemEventId": 443681075,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160706&eventSerialNumber=443681075&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 5002261,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "GETT",
                                        "debitAmount": 31.2,
                                        "debitAmountOffsetDiscount": 31.2,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 108,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160706,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-06T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 31.2,
                                        "originalSystemEventId": 444972340,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160706&eventSerialNumber=444972340&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 9743624,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "T N T הוניגמן",
                                        "debitAmount": 99.8,
                                        "debitAmountOffsetDiscount": 99.8,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 1,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160707,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-07T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 99.8,
                                        "originalSystemEventId": 446739501,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160707&eventSerialNumber=446739501&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 1101021,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "ELAL INT ISRAEL",
                                        "debitAmount": -2104.71,
                                        "debitAmountOffsetDiscount": -2104.71,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 13,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160707,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-07T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 2104.71,
                                        "originalSystemEventId": 447297939,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160707&eventSerialNumber=447297939&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 1556755,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "ELAL INT ISRAEL",
                                        "debitAmount": -2104.71,
                                        "debitAmountOffsetDiscount": -2104.71,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 13,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160707,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-07T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 2104.71,
                                        "originalSystemEventId": 447297940,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160707&eventSerialNumber=447297940&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 1556754,
                                        "serviceCode": 0
                                    },
                                    {
                                        "clientBusinessName": "GETT",
                                        "debitAmount": 36.9,
                                        "debitAmountOffsetDiscount": 36.9,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160802,
                                        "economicSectorCode": 108,
                                        "economySectorDescription": "",
                                        "eventCurrencyCode": 0,
                                        "eventCurrencyDescription": "NIS",
                                        "eventDate": 20160707,
                                        "formattedDebitDate": "2016-08-02T00:00:00.000Z",
                                        "formattedEventDate": "2016-07-07T00:00:00.000Z",
                                        "monthName": "",
                                        "nextDebitEventOriginalCode": 1,
                                        "originalAmount": 36.9,
                                        "originalSystemEventId": 447888011,
                                        "partyComments": [],
                                        "paymentCashBack": 0,
                                        "paymentNumber": 0,
                                        "paymentsNumber": 0,
                                        "pfmDetails": "/ServerServices/pfm/transactions?originalEventCreateDate=20160707&eventSerialNumber=447888011&dataOrigenCode=2&rejectedDataEventPertainingIndication=N",
                                        "previousDebitEventOriginalCode": "",
                                        "recordTypeCode": 0,
                                        "referenceNumber": 2756624,
                                        "serviceCode": 0
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        {
            "plasticCardNumberWithoutPrefix": "1309776849",
            "serviceCode": 0,
            "summary": {
                "current": {
                    "0": {
                        "serviceCode": 0,
                        "summariesByCurrencyCodes": {
                            "0": {
                                "serviceCode": 0,
                                "summaryDetails": {
                                    "0": {
                                        "accountCashBack": 0,
                                        "debitAmount": 0,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "",
                                        "debitDate": 0,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "",
                                        "formattedStatementDate": "",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 0,
                                        "partyComments": "6849  ישן",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 106,
                                        "plasticCardLable": "6849  ישן",
                                        "plasticCardNumberSuffix": "6849",
                                        "plasticCardNumberWithoutPrefix": 1309776849,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "",
                                        "serviceCode": 0,
                                        "statementDate": 0,
                                        "statusDescription": "פעיל"
                                    }
                                }
                            }
                        }
                    }
                },
                "prev": {
                    "1": {
                        "serviceCode": 0,
                        "summariesByCurrencyCodes": {
                            "0": {
                                "serviceCode": 0,
                                "summaryDetails": {
                                    "20160703": {
                                        "accountCashBack": 0,
                                        "debitAmount": 133.89,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160703,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "2016-07-03T00:00:00.000Z",
                                        "formattedStatementDate": "2016-07-10T00:00:00.000Z",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 0,
                                        "partyComments": "6849  ישן",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 0,
                                        "plasticCardLable": "",
                                        "plasticCardNumberSuffix": "6849",
                                        "plasticCardNumberWithoutPrefix": 1309776849,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "1",
                                        "serviceCode": 0,
                                        "statementDate": 20160710,
                                        "statusDescription": ""
                                    }
                                }
                            }
                        }
                    },
                    "2": {
                        "serviceCode": 0,
                        "summariesByCurrencyCodes": {
                            "0": {
                                "serviceCode": 0,
                                "summaryDetails": {
                                    "20160605": {
                                        "accountCashBack": 0,
                                        "debitAmount": 9.66,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160605,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "2016-06-05T00:00:00.000Z",
                                        "formattedStatementDate": "2016-07-10T00:00:00.000Z",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 0,
                                        "partyComments": "6849  ישן",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 0,
                                        "plasticCardLable": "",
                                        "plasticCardNumberSuffix": "6849",
                                        "plasticCardNumberWithoutPrefix": 1309776849,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "2",
                                        "serviceCode": 0,
                                        "statementDate": 20160710,
                                        "statusDescription": ""
                                    },
                                    "20160610": {
                                        "accountCashBack": 0,
                                        "debitAmount": 46.3,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160610,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "2016-06-10T00:00:00.000Z",
                                        "formattedStatementDate": "2016-07-10T00:00:00.000Z",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 0,
                                        "partyComments": "6849  ישן",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 0,
                                        "plasticCardLable": "",
                                        "plasticCardNumberSuffix": "6849",
                                        "plasticCardNumberWithoutPrefix": 1309776849,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "2",
                                        "serviceCode": 0,
                                        "statementDate": 20160710,
                                        "statusDescription": ""
                                    }
                                }
                            }
                        }
                    }
                },
                "serviceCode": 0
            },
            "vauchers": {}
        },
        {
            "plasticCardNumberWithoutPrefix": "30401446750",
            "serviceCode": 0,
            "summary": {
                "current": {
                    "0": {
                        "serviceCode": 0,
                        "summariesByCurrencyCodes": {
                            "0": {
                                "serviceCode": 0,
                                "summaryDetails": {
                                    "0": {
                                        "accountCashBack": 0,
                                        "debitAmount": 0,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "",
                                        "debitDate": 0,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "",
                                        "formattedStatementDate": "",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 0,
                                        "partyComments": "6750",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 115,
                                        "plasticCardLable": "6750",
                                        "plasticCardNumberSuffix": "6750",
                                        "plasticCardNumberWithoutPrefix": 30401446750,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "",
                                        "serviceCode": 0,
                                        "statementDate": 0,
                                        "statusDescription": "פעיל"
                                    }
                                }
                            }
                        }
                    }
                },
                "prev": {
                    "1": {
                        "serviceCode": 0,
                        "summariesByCurrencyCodes": {
                            "0": {
                                "serviceCode": 0,
                                "summaryDetails": {
                                    "20160703": {
                                        "accountCashBack": 0,
                                        "debitAmount": 209.42,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160703,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "2016-07-03T00:00:00.000Z",
                                        "formattedStatementDate": "2016-07-10T00:00:00.000Z",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 0,
                                        "partyComments": "6750",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 0,
                                        "plasticCardLable": "",
                                        "plasticCardNumberSuffix": "6750",
                                        "plasticCardNumberWithoutPrefix": 30401446750,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "1",
                                        "serviceCode": 0,
                                        "statementDate": 20160710,
                                        "statusDescription": ""
                                    }
                                }
                            }
                        }
                    },
                    "2": {
                        "serviceCode": 0,
                        "summariesByCurrencyCodes": {
                            "0": {
                                "serviceCode": 0,
                                "summaryDetails": {
                                    "20160603": {
                                        "accountCashBack": 0,
                                        "debitAmount": 11.94,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160603,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "2016-06-03T00:00:00.000Z",
                                        "formattedStatementDate": "2016-07-10T00:00:00.000Z",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 0,
                                        "partyComments": "6750",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 0,
                                        "plasticCardLable": "",
                                        "plasticCardNumberSuffix": "6750",
                                        "plasticCardNumberWithoutPrefix": 30401446750,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "2",
                                        "serviceCode": 0,
                                        "statementDate": 20160710,
                                        "statusDescription": ""
                                    },
                                    "20160608": {
                                        "accountCashBack": 0,
                                        "debitAmount": 39.89,
                                        "debitCurrencyCode": 0,
                                        "debitCurrencyDescription": "ש\"ח",
                                        "debitDate": 20160608,
                                        "formattedDebitAmount": "",
                                        "formattedDebitDate": "2016-06-08T00:00:00.000Z",
                                        "formattedStatementDate": "2016-07-10T00:00:00.000Z",
                                        "mobileFormattedDebitDate": "",
                                        "nextDebitEventOriginalCode": 0,
                                        "partyComments": "6750",
                                        "plasticCardBalanceAmount": 0,
                                        "plasticCardImageCode": 0,
                                        "plasticCardLable": "",
                                        "plasticCardNumberSuffix": "6750",
                                        "plasticCardNumberWithoutPrefix": 30401446750,
                                        "plasticCardStatusCode": 0,
                                        "poalimBankPlasticCardGroupCode": 1,
                                        "previousDebitEventOriginalCode": "2",
                                        "serviceCode": 0,
                                        "statementDate": 20160710,
                                        "statusDescription": ""
                                    }
                                }
                            }
                        }
                    }
                },
                "serviceCode": 0
            },
            "vauchers": {}
        }
    ],
    "serviceCode": 0
}
